const express = require("express");
const router = express.Router();
const Consultation = require("../models/Consultations");
const auth = require("../middleware/auth");

const { v4: uuidv4 } = require("uuid");

router.get("/", async(req, res)=>{

  const result = await Consultation.find()
  res.json(result)
} )


// Create a new consultation (roomId generated by backend)
router.post("/",  async (req, res) => {

  console.log("lasdlad")
  try {
    const { patient, doctor, mode, appointmentTime, reason } = req.body;

    // Generate a unique room ID
    const roomId = `room-${uuidv4()}`;

    const consultation = await Consultation.create({
      patient,
      doctor,
      mode,
      appointmentTime,
      reason,
      roomId,
    });

    res.status(201).json(consultation);
  } catch (err) {
    console.log(err.message)
    res.status(500).json({ message: "Failed to create consultation", error: err.message });
  }
});

// 2️⃣ Get consultations for a doctor
router.get("/doctor/:doctorId", auth, async (req, res) => {
  try {
    const consultations = await Consultation.find({ doctor: req.params.doctorId }).sort({ appointmentTime: 1 });
    res.json(consultations);
  } catch (err) {
    res.status(500).json({ message: "Failed to fetch consultations", error: err.message });
  }
});

// 3️⃣ Get consultations for a patient
router.get("/patient/:patientId", auth, async (req, res) => {
  try {
    const consultations = await Consultation.find({ patient: req.params.patientId }).sort({ appointmentTime: 1 });
    res.json(consultations);
  } catch (err) {
    res.status(500).json({ message: "Failed to fetch consultations", error: err.message });
  }
});

// 4️⃣ Cancel consultation
router.put("/:id/cancel", auth, async (req, res) => {
  try {
    const consultation = await Consultation.findByIdAndUpdate(
      req.params.id,
      { status: "cancelled", updatedAt: new Date() },
      { new: true }
    );
    res.json(consultation);
  } catch (err) {
    res.status(500).json({ message: "Failed to cancel consultation", error: err.message });
  }
});

// 5️⃣ Reschedule consultation
router.put("/:id/reschedule", auth, async (req, res) => {
  try {
    const { appointmentTime } = req.body;
    const consultation = await Consultation.findByIdAndUpdate(
      req.params.id,
      { appointmentTime, status: "scheduled", updatedAt: new Date() },
      { new: true }
    );
    res.json(consultation);
  } catch (err) {
    res.status(500).json({ message: "Failed to reschedule consultation", error: err.message });
  }
});

// 6️⃣ Delete consultation (optional)
router.delete("/:id", auth, async (req, res) => {
  try {
    await Consultation.findByIdAndDelete(req.params.id);
    res.json({ message: "Consultation deleted successfully" });
  } catch (err) {
    res.status(500).json({ message: "Failed to delete consultation", error: err.message });
  }
});

module.exports = router;
