const express = require('express');
const router = express.Router();
const HealthAlert = require('../models/HealthAlert');
const auth = require('../middleware/auth');
const HealthMonitoringScheduler = require('../services/HealthMonitoringScheduler');

/**
 * HEALTH ALERTS API
 * Endpoints for managing health alerts generated by the monitoring algorithm
 */

// GET /api/health-alerts - Get all alerts for current user
router.get('/', auth, async (req, res) => {
  try {
    const { limit = 50, skip = 0, unreadOnly = false } = req.query;
    const userId = req.userId;

    let query = { user: userId };
    if (unreadOnly === 'true') {
      query.read = false;
    }

    const alerts = await HealthAlert.find(query)
      .sort({ createdAt: -1 })
      .limit(parseInt(limit))
      .skip(parseInt(skip));

    const total = await HealthAlert.countDocuments(query);

    res.json({
      alerts,
      pagination: {
        total,
        limit: parseInt(limit),
        skip: parseInt(skip),
        unread: await HealthAlert.countDocuments({ user: userId, read: false }),
      },
    });
  } catch (err) {
    console.error('Error fetching alerts:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// GET /api/health-alerts/unread - Get count of unread alerts
router.get('/unread/count', auth, async (req, res) => {
  try {
    const userId = req.userId;

    const unreadCount = await HealthAlert.countDocuments({
      user: userId,
      read: false,
    });

    const criticalCount = await HealthAlert.countDocuments({
      user: userId,
      read: false,
      severity: 'critical',
    });

    res.json({
      unreadCount,
      criticalCount,
    });
  } catch (err) {
    console.error('Error getting unread count:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// GET /api/health-alerts/:id - Get specific alert
router.get('/:id', auth, async (req, res) => {
  try {
    const userId = req.userId;
    const alertId = req.params.id;

    const alert = await HealthAlert.findById(alertId);

    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }

    if (alert.user.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized' });
    }

    res.json({ alert });
  } catch (err) {
    console.error('Error fetching alert:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// PATCH /api/health-alerts/:id/read - Mark alert as read
router.patch('/:id/read', auth, async (req, res) => {
  try {
    const userId = req.userId;
    const alertId = req.params.id;

    const alert = await HealthAlert.findById(alertId);

    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }

    if (alert.user.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized' });
    }

    alert.read = true;
    await alert.save();

    res.json({ message: 'Alert marked as read', alert });
  } catch (err) {
    console.error('Error marking alert as read:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// PATCH /api/health-alerts/:id/action-taken - Mark action as taken
router.patch('/:id/action-taken', auth, async (req, res) => {
  try {
    const userId = req.userId;
    const alertId = req.params.id;
    const { actionDetails } = req.body;

    const alert = await HealthAlert.findById(alertId);

    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }

    if (alert.user.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized' });
    }

    alert.actionTaken = true;
    if (actionDetails) {
      alert.data = { ...alert.data, actionDetails };
    }
    await alert.save();

    res.json({ message: 'Action recorded', alert });
  } catch (err) {
    console.error('Error recording action:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// PATCH /api/health-alerts/mark-all-read - Mark all alerts as read
router.patch('/all/read', auth, async (req, res) => {
  try {
    const userId = req.userId;

    const result = await HealthAlert.updateMany(
      { user: userId, read: false },
      { read: true }
    );

    res.json({
      message: `Marked ${result.modifiedCount} alerts as read`,
      modifiedCount: result.modifiedCount,
    });
  } catch (err) {
    console.error('Error marking all alerts as read:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// GET /api/health-alerts/stats/summary - Get alert statistics
router.get('/stats/summary', auth, async (req, res) => {
  try {
    const userId = req.userId;

    const stats = {
      total: await HealthAlert.countDocuments({ user: userId }),
      unread: await HealthAlert.countDocuments({ user: userId, read: false }),
      critical: await HealthAlert.countDocuments({
        user: userId,
        severity: 'critical',
      }),
      warning: await HealthAlert.countDocuments({
        user: userId,
        severity: 'warning',
      }),
      info: await HealthAlert.countDocuments({
        user: userId,
        severity: 'info',
      }),
      byType: {
        medication: await HealthAlert.countDocuments({
          user: userId,
          type: 'medication_reminder',
        }),
        vitals: await HealthAlert.countDocuments({
          user: userId,
          type: { $in: ['vital_abnormal', 'vital_warning'] },
        }),
        progress: await HealthAlert.countDocuments({
          user: userId,
          type: 'progress_update',
        }),
        insights: await HealthAlert.countDocuments({
          user: userId,
          type: 'health_insight',
        }),
      },
    };

    res.json(stats);
  } catch (err) {
    console.error('Error getting alert stats:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// DELETE /api/health-alerts/:id - Delete alert
router.delete('/:id', auth, async (req, res) => {
  try {
    const userId = req.userId;
    const alertId = req.params.id;

    const alert = await HealthAlert.findById(alertId);

    if (!alert) {
      return res.status(404).json({ message: 'Alert not found' });
    }

    if (alert.user.toString() !== userId.toString()) {
      return res.status(403).json({ message: 'Unauthorized' });
    }

    await HealthAlert.findByIdAndDelete(alertId);

    res.json({ message: 'Alert deleted' });
  } catch (err) {
    console.error('Error deleting alert:', err);
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

/**
 * ADMIN ENDPOINTS (Requires admin authentication)
 */

// GET /api/health-alerts/admin/scheduler-status - Get scheduler status
router.get('/admin/scheduler-status', async (req, res) => {
  try {
    // TODO: Add admin auth middleware
    const status = HealthMonitoringScheduler.getStatus();
    res.json(status);
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// POST /api/health-alerts/admin/trigger-check - Manually trigger health check
router.post('/admin/trigger-check', async (req, res) => {
  try {
    // TODO: Add admin auth middleware
    const result = await HealthMonitoringScheduler.runManually();
    res.json({
      message: 'Health check triggered manually',
      result,
    });
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// POST /api/health-alerts/admin/start-scheduler - Start scheduler
router.post('/admin/start-scheduler', async (req, res) => {
  try {
    // TODO: Add admin auth middleware
    HealthMonitoringScheduler.start();
    res.json({ message: 'Scheduler started' });
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// POST /api/health-alerts/admin/stop-scheduler - Stop scheduler
router.post('/admin/stop-scheduler', async (req, res) => {
  try {
    // TODO: Add admin auth middleware
    HealthMonitoringScheduler.stop();
    res.json({ message: 'Scheduler stopped' });
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

module.exports = router;
